apiVersion: v1
kind: ConfigMap
metadata:
  name: weaviate-config
data:
  conf.yaml: |-
    ---
    database:
      name: janusgraph
      database_config:
        url: http://{{ .Release.Name }}-janusgraph:8182
    authentication:
{{ toYaml .Values.authentication | indent 6 }}
    authorization:
{{ toYaml .Values.authorization | indent 6 }}
    configuration_storage:
      type: etcd
      url: http://{{ .Release.Name }}-etcd:2379
    contextionary:
{{ toYaml .Values.contextionary | indent 6 }}
    query_defaults:
{{ toYaml .Values.query_defaults | indent 6 }}
    debug: {{ .Values.debug }}
    telemetry:
{{ toYaml .Values.telemetry | indent 6 }}
