apiVersion: v1
kind: ConfigMap
metadata:
  name: weaviate-config
data:
  conf.yaml: |-
    ---
    database:
      name: janusgraph
      database_config:
        url: http://{{ template "janusgraph.fullname" . }}-janusgraph:8182
    authentication:
      anonymous_access:
        enabled: true
    configuration_storage:
      type: etcd
      url: http://weaviate-etcd:2379
    contextionary:
      knn_file: "{{ .Values.contextionary.knnFile }}"
      idx_file: "{{ .Values.contextionary.idxFile }}"
    limit: 100
    debug: false
    telemetry:
      disabled: true
