apiVersion: v1
kind: ConfigMap
metadata:
  name: weaviate-config
data:
  conf.yaml: |-
    ---
    database:
      name: janusgraph
      database_config:
        url: http://{{ .Release.Name }}-janusgraph:8182
    authentication:
      {{ toYaml .Values.authentication | nindent 6 | trim }}
    authorization:
      {{ toYaml .Values.authorization | nindent 6 | trim }}
    configuration_storage:
      type: etcd
      url: http://{{ .Release.Name }}-etcd:2379
    contextionary:
      url: contextionary:9999
    query_defaults:
      {{ toYaml .Values.query_defaults | nindent 6 | trim }}
    debug: {{ .Values.debug }}
    telemetry:
      {{ toYaml .Values.telemetry | nindent 6 | trim }}
    vector_index:
      enabled: {{ .Values.vector_index.enabled }}
      url: http://esvector-master:9200
