resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "1000m"
    memory: "500Mi"

#esvector
esvector:
  esJavaOpts: -Xmx512m -Xms512m
  minimumMasterNodes: 1
  replicas: 1
  resources: 
    requests:
      memory: 512Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 1
  volumeClaimTemplate:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 150Gi

etcd:
  statefulset:
    replicaCount: 1

contextionary:
  resources:
    requests:
      cpu: "100m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "5000Mi"
