
cassandra:
  config:
    cluster_size: 1
    seed_size: 1
    start_rpc: true
    max_heap_size: 256M
    heap_new_size: 128M
  resources:
    requests:
      memory: 0.5Gi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: 500m

#Elasticsearch
elasticsearch:
  esJavaOpts: -Xmx512m -Xms512m
  minimumMasterNodes: 1
  replicas: 1
  resources: 
    requests:
      memory: 512Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 1

#esvector
esvector:
  esJavaOpts: -Xmx512m -Xms512m
  minimumMasterNodes: 1
  replicas: 1
  resources: 
    requests:
      memory: 512Mi
      cpu: 100m
    limits:
      memory: 1Gi
      cpu: 1

janusgraph:
  resources:
    requests:
      memory: 0.5Gi
      cpu: 200m
    limits:
      memory: 2Gi
      cpu: 500m

etcd:
  statefulset:
    replicaCount: 1
